defaults:
  - override hydra/job_logging: custom
  - _self_


# global
seed: 2024
device: 0
debug: False
mixed_precision: False

# train
train_conf:
  only_first_fold: False
  n_folds: 5
  epochs: 10
  val_interval: 0.5

# data
data_conf:
  data_root: './data'
  n_max: -1
  v_dataset: 'v1'
  v_speed: 'v1'
  v_field: 'v1'
  batch_size: 10
  num_workers: 4
  pin_memory: True
  persistent_workers: True
  preprocess: 'None'

# model
model_type: 'fno'
load_conf:
  load: False
  folder: 'None'
fno_conf:
  input_dim: 6
  lifting_size: 20
  lifting: None
  proj: None
  wavenumber: [30, 30, 30, 30, 30, 30, 30]
  padding: 32
  activation: relu
  use_bn: False
  simplified_fourier: False
kanfno_conf:
  input_dim: 6
  lifting_size: 20
  lifting: None
  proj: None
  wavenumber: [30, 30, 30, 30, 30, 30, 30]
  padding: 32
  activation: relu
  grid_size: 3
  load_weights: False
  ckpt_folder: None
  fixed_backbone: False
  use_bn: False
afno_conf:
  patch_size: [16, 16]
  embed_dim: 256
  depth: 4
  mlp_ratio: 4.0
  drop_rate: 0.0
  num_blocks: 16
  sparsity_threshold: 0.01
  hard_thresholding_fraction: 1.0
hrnet_conf:
  INPUT_CHANNEL: 6
  OUT_CHANNEL: 2
  STEM_INPLANES: 64
  FINAL_CONV_KERNEL: 1
  WITH_HEAD: True
  STAGE1:
    NUM_MODULES: 1
    NUM_BRANCHES: 1
    NUM_BLOCKS: [ 4 ]
    NUM_CHANNELS: [ 32 ]
    BLOCK: 'BASIC'
    FUSE_METHOD: 'SUM'
  STAGE2:
    NUM_MODULES: 1
    NUM_BRANCHES: 2
    NUM_BLOCKS: [ 4, 4 ]
    NUM_CHANNELS: [ 32, 64 ]
    BLOCK: 'BASIC'
    FUSE_METHOD: 'SUM'
  STAGE3:
    NUM_MODULES: 1
    NUM_BRANCHES: 3
    NUM_BLOCKS: [ 4, 4, 4 ]
    NUM_CHANNELS: [ 32, 64, 128 ]
    BLOCK: 'BASIC'
    FUSE_METHOD: 'SUM'
  STAGE4:
    NUM_MODULES: 1
    NUM_BRANCHES: 4
    NUM_BLOCKS: [ 4, 4, 4, 4 ]
    NUM_CHANNELS: [ 32, 64, 128, 256 ]
    BLOCK: 'BASIC'
    FUSE_METHOD: 'SUM'

# loss
loss_conf:
  loss_type: 'l2'


# optimizer
optim_conf:
  type: 'adam'
  lr: 1e-2
  weight_decay: 1e-5
  scheduler: 'cosine'



hydra:
  job:
    chdir: True
